# Namespace onde o recurso será criado (opcional, pode ser definido no ArgoCD)
namespace: ""

image:
  repository: mysql
  tag: "8.0"

auth:
  rootPassword: root
  database: principaldb
  user: appuser
  password: Andor@12345

service:
  type: ClusterIP  # ClusterIP, NodePort ou LoadBalancer
  port: 3306
  nodePort: null  # Apenas necessário se type for NodePort

persistence:
  enabled: true
  size: 5Gi
