apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.auth.rootPassword }}
  MYSQL_DATABASE: {{ .Values.auth.database }}
  MYSQL_USER: {{ .Values.auth.username }}
  MYSQL_PASSWORD: {{ .Values.auth.password }}
