apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ include "mysql.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mysql.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "mysql.fullname" . }}
    spec:
      serviceAccountName: {{ include "mysql.fullname" . }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: {{ include "mysql.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mysql.fullname" . }}-pvc
