# Namespace onde o recurso será criado (opcional, pode ser definido no ArgoCD)
namespace: ""

image:
  repository: postgres
  tag: "16"

auth:
  user: postgres
  password: Andor@12345
  database: principaldb

service:
  type: ClusterIP  # ClusterIP, NodePort ou LoadBalancer
  port: 5432
  nodePort: null  # Apenas necessário se type for NodePort

persistence:
  enabled: true
  size: 5Gi
