apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.auth.password }}
  POSTGRES_DB: {{ .Values.auth.database }}
